name: ci

on:
  push:
    branches: [main]
  pull_request:

# env:
  # ImageOs must be configured to match the OS of the runner when using self-hosted runners.
  # ImageOS: ubuntu22

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: ruby
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: bundle install
      - name: Run specs
        run: bin/rspec
  lint:
    runs-on: ubuntu-latest
    container: ruby
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: bundle install
      - name: Lint
        run: bin/rubocop
